### ISSUE TITLE
Can't convert model ViT KPRPE to onnx

### ISSUE THREAD

**Issue by HuyNgQc** [mk-minchul/CVLface#1]
I convert model ViT KPRPE to onnx. But when opening the model with netron, the structure of this model is wrong, the network only has 1 input (I think there should be 2 inputs are image and landmarks).

**Comment by mk-minchul** [comment]
Thanks for the effort. It is correct that the network takes 2 inputs. While we do not support netron out of the box, please feel free to PR any updates regarding opening the model with netron.
