### ISSUE TITLE
will the top model be released?

### ISSUE THREAD

**Issue by NIKHILDUGAR** [mk-minchul/CVLface#15]
Will the ViT KPRPE AdaFace trained on WebFace12M mentioned [here](https://github.com/mk-minchul/CVLface/blob/37eca7364666f401de06020fdd3cd91fa288c2ce/cvlface/pretrained_models/README.md#face-recognition-performance-board) be made publicly available?

**Comment by mk-minchul** [comment]
It is released. Thanks for the interest in our paper.
