### ISSUE TITLE
new 12m model is same as 4m model on huggingface?

### ISSUE THREAD

**Issue by cfivek** [mk-minchul/CVLface#19]
https://huggingface.co/minchul/cvlface_adaface_vit_base_kprpe_webface4m/blob/main/model.safetensors
Git LFS Details

    SHA256: 3c6d37ea874c2f38ffc9a7f0e9247efc994c3fb5c12d044759ac294e19d127f7
    Pointer size: 134 Bytes
    Size of remote file: 460 MB

https://huggingface.co/minchul/cvlface_adaface_vit_base_kprpe_webface12m/blob/main/model.safetensors
Git LFS Details

    SHA256: 99d16ed4aac0fdf0fcc82526b9b70703f3ec8c3041bf1bf44bd22751536e65db
    Pointer size: 134 Bytes
    Size of remote file: 460 MB

Different hash but size is the same.

Shouldnt the 12m model be larger? In adaface it was.

**Comment by mk-minchul** [comment]
Hi. They should be the same size as they are same model with different training dataset. Both are ViT Base.

**Comment by cfivek** [comment]
Thank you

**Comment by cfivek** [comment]
Thank you
