### ISSUE TITLE
eval datasets link broken again

### ISSUE THREAD

**Issue by cfivek** [mk-minchul/CVLface#27]
https://drive.google.com/file/d/1NSjSs__RlgJjGPJTWCY9EzTJUx-WRuaq/view?usp=sharing 

this link for evaluation datasets from the CVLface docs is dead.. it's found in this area of docs https://mk-minchul.github.io/CVLface/#/pages/eval_datasets?id=accessing-the-password-for-the-zip-file

Thx

**Comment by mk-minchul** [comment]
Thanks for pointing it out. Try this link. https://drive.google.com/file/d/1oEvQdseNhcWdBh2X7l2bMK_BfBZX8JCZ/view?usp=sharing until the documentation is updated.

**Comment by cfivek** [comment]
Thanks. I'm getting this issue though.

Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by cfivek** [comment]
thanks. works now
