### ISSUE TITLE
Password Evaluation Toolkit

### ISSUE THREAD

**Issue by kingjan1999** [mk-minchul/CVLface#3]
Hi,

I wanted to reproduce your results using the provided evaluation toolkit.

However, I'm not quite sure how to acquire the password for the zip file. The [README](https://github.com/mk-minchul/CVLface/blob/main/cvlface/data_utils/recognition/eval_data/README_EVAL_TOOLKIT.md) points to a Google Form, but after submitting the form nothing happens? I'd have expected the password to be displayed.

**Comment by mk-minchul** [comment]
Thank you for brining it up :) The form was not correctly set up. It is fixed now and you should be able to see the password once you submit for form.
